---
custom_packages:
  tmux:     {}
  htop:     {}
  mlocate:  {}
custom_users:
  raymond:
    group: users
custom_authorized_keys:
  raymond: {}
custom_sudoers:
  raymond: {}
sshd:
  GSSAPIAuthentication: no
  X11Forwarding: yes
  PasswordAuthentication: no
  AllowAgentForwarding: yes
